
name: Deploy release

on:
  push:
    tags:
      - '*'

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.x"
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install dependencies
        run: make install

      - name: Build app 
        run: make build

      - name: Change execution permissions
        run: chmod +x ./scripts/create_release.sh

      - name: Create release and upload assets 
        env:
          github_token: ${{ secrets.GH_TOKEN }}
        run: ./scripts/create_release.sh "${{ env.github_token }}"  ${{ github.ref }} ""

